name: Test

on: push

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: denolib/setup-deno@v2
        with:
          deno-version: '0.40'
      - if: matrix.os != 'windows-latest'
        run: deno run --allow-read --allow-write https://denopkg.com/wyze/conditional_bisect@v1.0.1/mod.ts
      - run: yarn install
      - if: matrix.os != 'windows-latest'
        run: yarn add bisect_ppx
      - run: yarn build
      - run: yarn test
